const tableData = [
  {
    dataId: 234,
    network: "mtn",
    plan_type: "sme",
    amount: "₦245",
    size: "1.0 gb",
    duration: "30 days",
  },
  {
    dataId: 235,
    network: "mtn",
    plan_type: "sme",
    amount: "₦490",
    size: "2.0 gb",
    duration: "30 days",
  },
  // {
  //   dataId: 44,
  //   network: "mtn",
  //   plan_type: "sme",
  //   amount: "₦725",
  //   size: "3.0 gb",
  //   duration: "30 days",
  // },
  {
    dataId: 237,
    network: "mtn",
    plan_type: "sme",
    amount: "₦1250",
    size: "5.0 gb",
    duration: "30 days",
  },
  {
    dataId: 246,
    network: "mtn",
    plan_type: "sme",
    amount: "₦2450",
    size: "10.0 gb",
    duration: "30 days",
  },
  {
    dataId: 257,
    network: "airtel",
    plan_type: "gifting",
    amount: "₦50",
    size: "100.0 mb",
    duration: "7 days",
  },
  {
    dataId: 258,
    network: "airtel",
    plan_type: "gifting",
    amount: "₦100",
    size: "300.0 mb",
    duration: "7 days",
  },
  {
    dataId: 253,
    network: "airtel",
    plan_type: "gifting",
    amount: "₦200",
    size: "500.0 mb",
    duration: "monthly",
  },
  {
    dataId: 254,
    network: "airtel",
    plan_type: "gifting",
    amount: "₦380",
    size: "1.0 gb",
    duration: "monthly",
  },
  {
    dataId: 255,
    network: "airtel",
    plan_type: "gifting",
    amount: "₦760",
    size: "2.0 gb",
    duration: "monthly",
  },
  {
    dataId: 256,
    network: "airtel",
    plan_type: "gifting",
    amount: "₦1850",
    size: "5.0 gb",
    duration: "monthly",
  },
  {
    dataId: "208",
    network: "mtn",
    amount: "₦255",
    plan_type: "gifting",
    size: "1.0 gb",
    duration: "monthly",
  },
  {
    dataId: "209",
    network: "mtn",
    amount: "₦510",
    plan_type: "gifting",
    size: "2.0 gb",
    duration: "monthly",
  },
  {
    dataId: "210",
    network: "mtn",
    amount: "₦765",
    plan_type: "gifting",
    size: "3.0 gb",
    duration: "monthly",
  },
  {
    dataId: "211",
    network: "mtn",
    amount: "₦1275",
    plan_type: "gifting",
    size: "5.0 gb",
    duration: "monthly",
  },
  {
    dataId: "43",
    network: "mtn",
    amount: "₦2500",
    plan_type: "gifting",
    size: "10.0 gb",
    duration: "monthly",
  },
];

export const tableDataWhole = [
  {
    dataId: 227,
    network: "mtn",
    plan_type: "Cooperate Gifting",
    price: "₦235/GB",
    package: "Silver Seller",
    purchase_range: "1TB - 10TB",
  },
  {
    dataId: 228,
    network: "mtn",
    plan_type: "Cooperate Gifting",
    price: "₦230/GB",
    package: "Gold Seller",
    purchase_range: "50TB - 100TB",
  },
  {
    dataId: 229,
    network: "Airtel",
    plan_type: "Cooperate Gifting",
    price: "₦350/GB",
    package: "Bronze Seller",
    purchase_range: "1TB - 10TB",
  },
  {
    dataId: 230,
    network: "Airtel",
    plan_type: "Cooperate Gifting",
    price: "₦330/GB",
    package: "Silver Seller",
    purchase_range: "10TB - 50TB",
  },
  {
    dataId: 231,
    network: "Airtel",
    plan_type: "Cooperate Gifting",
    price: "₦300/GB",
    package: "Gold Seller",
    purchase_range: "50TB - 100TB",
  },
];

export default tableData;

// const tableData_old = [
//   {
//     dataId: 7,
//     network: "mtn",
//     plan_type: "sme",
//     amount: "₦245",
//     size: "1.0 gb",
//     duration: "30 days",
//   },
//   {
//     dataId: 8,
//     network: "mtn",
//     plan_type: "sme",
//     amount: "₦490",
//     size: "2.0 gb",
//     duration: "30 days",
//   },
//   {
//     dataId: 44,
//     network: "mtn",
//     plan_type: "sme",
//     amount: "₦725",
//     size: "3.0 gb",
//     duration: "30 days",
//   },
//   {
//     dataId: 11,
//     network: "mtn",
//     plan_type: "sme",
//     amount: "₦1250",
//     size: "5.0 gb",
//     duration: "30 days",
//   },
//   {
//     dataId: 220,
//     network: "mtn",
//     plan_type: "sme",
//     amount: "₦2450",
//     size: "10.0 gb",
//     duration: "30 days",
//   },
//   {
//     dataId: 225,
//     network: "airtel",
//     plan_type: "gifting",
//     amount: "₦50",
//     size: "100.0 mb",
//     duration: "7 days",
//   },
//   {
//     dataId: 226,
//     network: "airtel",
//     plan_type: "gifting",
//     amount: "₦100",
//     size: "300.0 mb",
//     duration: "7 days",
//   },
//   {
//     dataId: 221,
//     network: "airtel",
//     plan_type: "gifting",
//     amount: "₦200",
//     size: "500.0 mb",
//     duration: "monthly",
//   },
//   {
//     dataId: 222,
//     network: "airtel",
//     plan_type: "gifting",
//     amount: "₦380",
//     size: "1.0 gb",
//     duration: "monthly",
//   },
//   {
//     dataId: 223,
//     network: "airtel",
//     plan_type: "gifting",
//     amount: "₦760",
//     size: "2.0 gb",
//     duration: "monthly",
//   },
//   {
//     dataId: 224,
//     network: "airtel",
//     plan_type: "gifting",
//     amount: "₦1850",
//     size: "5.0 gb",
//     duration: "monthly",
//   },
//   {
//     dataId: "217",
//     network: "mtn",
//     amount: "₦255",
//     plan_type: "gifting",
//     size: "1.0 gb",
//     duration: "monthly",
//   },
//   {
//     dataId: "209",
//     network: "mtn",
//     amount: "₦510",
//     plan_type: "gifting",
//     size: "2.0 gb",
//     duration: "monthly",
//   },
//   {
//     dataId: "210",
//     network: "mtn",
//     amount: "₦765",
//     plan_type: "gifting",
//     size: "3.0 gb",
//     duration: "monthly",
//   },
//   {
//     dataId: "211",
//     network: "mtn",
//     amount: "₦1275",
//     plan_type: "gifting",
//     size: "5.0 gb",
//     duration: "monthly",
//   },
//   {
//     dataId: "43",
//     network: "mtn",
//     amount: "₦2500",
//     plan_type: "gifting",
//     size: "10.0 gb",
//     duration: "monthly",
//   },
// ];